include:
  - board: nice_nano//zmk
    shield: simply_adept_left
    # Add these cmake-args to the peripherals you wish to use with the dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifect-name: simply_adept_left

  - board: nice_nano//zmk
    shield: simply_adept_right
    # Add these cmake-args to the peripherals you wish to use with the dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifect-name: simply_adept_right

  - board: xiao_ble//zmk
    shield: simply_adept_trackball
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifect-name: simply_adept_trackball

  - board: xiao_ble//zmk
    shield: simply_adept_dongle prospector_adapter
    # uart snippet needed on central side for ZMK studio to work
    snippet: zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifect-name: simply_adept_prospector_dongle

  - board: nice_nano//zmk
    shield: settings_reset
    artifect-name: trackball_dongle_reset

  - board: xiao_ble//zmk
    shield: settings_reset
    artifect-name: splits_reset