include:
  - board: nice_nano
    shield: simply_adept_left
    # Add these cmake-args to the peripherals you wish to use with the dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: simply_adept_left

  - board: nice_nano
    shield: simply_adept_right
    # Add these cmake-args to the peripherals you wish to use with the dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: simply_adept_right

  - board: seeeduino_xiao_ble
    shield: simply_adept_trackball
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: simply_adept_trackball

  - board: seeeduino_xiao_ble
    shield: simply_adept_dongle prospector_adapter
    # uart snippet needed on central side for ZMK studio to work
    snippet: zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: simply_adept_prospector_dongle

  - board: nice_nano
    shield: settings_reset
    artifact-name: trackball_dongle_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: splits_reset